### PR TITLE
Add DATS to Matlab docs

### PR DESCRIPTION
**Pull request by Adithya1610**
Added docs to run the python script to convert DATS file to MAT file

### CODE REVIEW

**Review by ApocalyVec — CHANGES_REQUESTED** [review]
Add the page to 'Further Information' in index.rst for easier navigation.

**Comment by Adithya1610** [comment]
Done

**Review by ApocalyVec — CHANGES_REQUESTED** [review]
Please add link to the instruction for installing conda as in-line links.

Add instruction for load .m file in matlab for completeness.

Use rst code block for the console commands listed, refer to other pages in the doc for the format.

Actually, the instruction for setting up ReNa's environment is covered in the GetStarted page (index.rst). But it did not cover setting up a virtual environment, please move the 'setting up virtual environment' part to GetStarted and link to it from the matlab instructions.

**Review by ApocalyVec — COMMENTED** [review]
Now we are making the GUI release, consider adding a 'save format' option in the recording tab of the GUI. User can choose from .dats or .mat or both.

**Pull request merged**
